name: SPIKE ðŸ”
description: A dicision needs to be made
title: "[SPIKE] "

body:
- type: markdown
  attributes:
    value: |
      For more info on how to use a SPIKE look [here](https://docs.woosmap.dev/how_we_work/issues/#spikes)
- type: textarea
  attributes:
    label: Question
    description: The Question to be answered.
  validations:
    required: true
- type: textarea
  attributes:
    label: Possible Solutions
    description: The list of possible solutions to persue, it could just be one.
- type: textarea
  attributes:
    label: Outcomes
    description: The result of each solution tried.
    value: |
      - [ ] #1
- type: textarea
  attributes:
    label: Decision Makers
    description: The list of people who should make the choice once given the outcomes.
- type: textarea
  attributes:
    label: Chosen Solution
    description: The Solition chosen and why.
- type: markdown
  attributes:
    value: |
      Thanks for completing our form!
      Don't forget to select the project on the right ->
      and to then, if possible, fill in the project fields.